### ISSUE TITLE
Error when placing block (and no sound)

### ISSUE THREAD

**Issue by Twiz0x** [ViaVersion/ViaRewind-Legacy-Support#10]
Hey! I'm using TacoSpigot 1.9.4, and I have no sound when I try to place block, there is an error:

Config:
brewing-stand-gui-fix: true
enchanting-gui-fix: true
lily-pad-fix: true
ladder-fix: true
sound-fix: true
slime-fix: true
elytra-fix: true
area-effect-cloud-particles: true
versioninfo:
  active: false
  max-version: 47
  interval: JOIN
  message: '&7[&6Info&7] This server is running Minecraft %version%. The best gameplay
    experience is only guaranteed if you are using this version.'

Error:

java.lang.NoSuchMethodException: net.minecraft.server.v1_9_R2.BlockSand.getStepSound()
[12:54:17 WARN]:        at java.base/java.lang.Class.newNoSuchMethodException(Class.java:641)
[12:54:17 WARN]:        at java.base/java.lang.Class.throwExceptionOrReturnNull(Class.java:1369)
[12:54:17 WARN]:        at java.base/java.lang.Class.getMethodHelper(Class.java:1455)
[12:54:17 WARN]:        at java.base/java.lang.Class.getMethod(Class.java:1361)
[12:54:17 WARN]:        at de.gerrygames.viarewind.legacysupport.listener.SoundListener.playBlockPlaceSound(SoundListener.java:107)
[12:54:17 WARN]:        at de.gerrygames.viarewind.legacysupport.listener.SoundListener.onBlockPlace(SoundListener.java:61)
[12:54:17 WARN]:        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor351.execute(Unknown Source)
[12:54:17 WARN]:        at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:44)
[12:54:17 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78)
[12:54:17 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[12:54:17 WARN]:        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517)
[12:54:17 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502)
[12:54:17 WARN]:        at org.bukkit.craftbukkit.v1_9_R2.event.CraftEventFactory.callBlockPlaceEvent(CraftEventFactory.java:146)
[12:54:17 WARN]:        at net.minecraft.server.v1_9_R2.ItemStack.placeItem(ItemStack.java:166)
[12:54:17 WARN]:        at net.minecraft.server.v1_9_R2.PlayerInteractManager.a(PlayerInteractManager.java:523)
[12:54:17 WARN]:        at net.minecraft.server.v1_9_R2.PlayerConnection.a(PlayerConnection.java:890)
[12:54:17 WARN]:        at net.minecraft.server.v1_9_R2.PacketPlayInUseItem.a(SourceFile:55)
[12:54:17 WARN]:        at net.minecraft.server.v1_9_R2.PacketPlayInUseItem.a(SourceFile:11)
[12:54:17 WARN]:        at net.minecraft.server.v1_9_R2.PlayerConnectionUtils$1.run(SourceFile:13)
[12:54:17 WARN]:        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[12:54:17 WARN]:        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[12:54:17 WARN]:        at net.minecraft.server.v1_9_R2.SystemUtils.a(SourceFile:45)
[12:54:17 WARN]:        at net.minecraft.server.v1_9_R2.MinecraftServer.D(MinecraftServer.java:786)
[12:54:17 WARN]:        at net.minecraft.server.v1_9_R2.DedicatedServer.D(DedicatedServer.java:403)
[12:54:17 WARN]:        at net.minecraft.server.v1_9_R2.MinecraftServer.C(MinecraftServer.java:723)
[12:54:17 WARN]:        at net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java:622)
[12:54:17 WARN]:        at java.base/java.lang.Thread.run(Thread.java:836)

**Comment by Twiz0x** [comment]
Fixed using the version 1.3.1, 1.3.2 and 1.3.3 are broken
