### ISSUE TITLE
java.lang.NoSuchMethodError on start

### ISSUE THREAD

**Issue by nathanfranke** [ViaVersion/ViaRewind-Legacy-Support#15]
File Setup:
- Paper-1.16.5-629.jar
- eula.txt
- plugins/
  - ViaVersion-3.2.2-506.jar
  - ViaBackwards-3.2.1-202.jar
  - ViaRewind-1.5.3-95.jar
  - ViaRewindLegacySupport-1.3.4-11.jar

Error:
```
[11:56:18 INFO]: [ViaVersion] Enabling ViaVersion v3.2.2-SNAPSHOT
[11:56:18 INFO]: [ViaRewind-Legacy-Support] Enabling ViaRewind-Legacy-Support v1.3.4
[11:56:18 INFO]: Running delayed init tasks
[11:56:18 INFO]: [ViaVersion] ViaVersion detected server version: 1.16.4 (754)
[11:56:18 WARN]: [ViaRewind-Legacy-Support] Task #22 for ViaRewind-Legacy-Support v1.3.4 generated an exception
java.lang.NoSuchMethodError: 'us.myles.ViaVersion.api.protocol.ServerProtocolVersion us.myles.ViaVersion.api.ViaAPI.getServerVersion()'
        at de.gerrygames.viarewind.legacysupport.BukkitPlugin$1.run(BukkitPlugin.java:30) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.16.5.jar:git-Paper-629]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.5.jar:git-Paper-629]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1074) ~[patched_1.16.5.jar:git-Paper-629]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:289) ~[patched_1.16.5.jar:git-Paper-629]
        at java.lang.Thread.run(Thread.java:832) [?:?]

```

Full log:
[latest.log](https://github.com/ViaVersion/ViaRewind-Legacy-Support/files/6393523/latest.log)

**Comment by PierreSchwang** [comment]
The issue seems to be fixed now - Use this artifact: https://github.com/ViaVersion/ViaRewind-Legacy-Support/suites/2620425892/artifacts/57424939

**Comment by nathanfranke** [comment]
I am not allowed to access that page

**Comment by PierreSchwang** [comment]
The latest build available currently.

**Comment by nathanfranke** [comment]
Okay, perfect.

**Comment by nathanfranke** [comment]
Using that artifact:

```
[15:55:21 WARN]: [ViaRewind-Legacy-Support] Task #142 for ViaRewind-Legacy-Support v1.4.0 generated an exception
java.lang.NoClassDefFoundError: com/viaversion/viaversion/api/Via
        at de.gerrygames.viarewind.legacysupport.BukkitPlugin$1.run(BukkitPlugin.java:30) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.16.5.jar:git-Paper-629]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.5.jar:git-Paper-629]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1074) ~[patched_1.16.5.jar:git-Paper-629]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:289) ~[patched_1.16.5.jar:git-Paper-629]
        at java.lang.Thread.run(Thread.java:832) [?:?]
Caused by: java.lang.ClassNotFoundException: com.viaversion.viaversion.api.Via
        at java.net.URLClassLoader.findClass(URLClassLoader.java:435) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:182) ~[patched_1.16.5.jar:git-Paper-629]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:111) ~[patched_1.16.5.jar:git-Paper-629]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:589) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?]
        ... 6 more
[15:55:21 INFO]: [ViaVersion] Finished mapping loading, shutting down loader executor!
[15:55:21 INFO]: Done (3.739s)! For help, type "help"
[15:55:21 INFO]: Timings Reset
[15:55:21 WARN]: [ViaRewind-Legacy-Support] Task #142 for ViaRewind-Legacy-Support v1.4.0 generated an exception
java.lang.NoClassDefFoundError: com/viaversion/viaversion/api/Via
        at de.gerrygames.viarewind.legacysupport.BukkitPlugin$1.run(BukkitPlugin.java:30) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.16.5.jar:git-Paper-629]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.5.jar:git-Paper-629]
        at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1423) ~[patched_1.16.5.jar:git-Paper-629]
        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:419) ~[patched_1.16.5.jar:git-Paper-629]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1338) ~[patched_1.16.5.jar:git-Paper-629]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1126) ~[patched_1.16.5.jar:git-Paper-629]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:289) ~[patched_1.16.5.jar:git-Paper-629]
        at java.lang.Thread.run(Thread.java:832) [?:?]

```

With latest dev builds for ViaVersion, ViaBackwards, ViaRewind, and the artifact you provided:
```
[15:57:41 ERROR]: Error occurred while enabling ViaRewind v2.0.0-SNAPSHOT (Is it up to date?)
java.lang.NoSuchFieldError: INT
        at de.gerrygames.viarewind.protocol.protocol1_8to1_9.Protocol1_8TO1_9.<clinit>(Protocol1_8TO1_9.java:44) ~[?:?]
        at de.gerrygames.viarewind.api.ViaRewindPlatform.init(ViaRewindPlatform.java:20) ~[?:?]
        at de.gerrygames.viarewind.BukkitPlugin.onEnable(BukkitPlugin.java:14) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.5.jar:git-Paper-629]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.5.jar:git-Paper-629]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.5.jar:git-Paper-629]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501) ~[patched_1.16.5.jar:git-Paper-629]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415) ~[patched_1.16.5.jar:git-Paper-629]
        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:253) ~[patched_1.16.5.jar:git-Paper-629]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1065) ~[patched_1.16.5.jar:git-Paper-629]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:289) ~[patched_1.16.5.jar:git-Paper-629]
        at java.lang.Thread.run(Thread.java:832) [?:?]

```

For now I am just using build 9 and non-dev Via, it is the only setup that works

**Comment by Jo0001** [comment]
Use the CI builds, otherwise open a new issues (with dump etc)
ViaVersion - https://ci.viaversion.com/job/ViaVersion/lastSuccessfulBuild/artifact/build/libs/ViaVersion-4.0.2-SNAPSHOT.jar
ViaBackwards - https://ci.viaversion.com/job/ViaBackwards/lastSuccessfulBuild/artifact/build/libs/ViaBackwards-4.0.2-SNAPSHOT.jar
ViaRewind - https://ci.viaversion.com/job/ViaRewind/lastSuccessfulBuild/artifact/all/target/ViaRewind-2.0.2-SNAPSHOT.jar
ViaRewind Legacy Support (Bukkit) - https://ci.viaversion.com/view/All/job/ViaRewind%20Legacy%20Support/lastSuccessfulBuild/artifact/target/viarewind-legacy-support-1.4.1.jar
