### ISSUE TITLE
Warnings in console

### ISSUE THREAD

**Issue by LeehamElectronics** [ViaVersion/ViaRewind-Legacy-Support#32]
Hi, is it possible to have these warnings removed?
Thanks
```
[14:21:14 INFO]: [ViaVersion] ViaVersion detected server version: 1.17.1 (756)
[14:21:14 WARN]: java.lang.ClassNotFoundException: net.minecraft.server.v1_17_R1.BlockWaterLily
[14:21:14 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:146)
[14:21:14 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103)
[14:21:14 WARN]:        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
[14:21:14 WARN]:        at java.base/java.lang.Class.forName0(Native Method)
[14:21:14 WARN]:        at java.base/java.lang.Class.forName(Class.java:375)
[14:21:14 WARN]:        at viarewind-legacy-support-1.4.0.jar//de.gerrygames.viarewind.legacysupport.injector.NMSReflection.getNMSClass(NMSReflection.java:15)
[14:21:14 WARN]:        at viarewind-legacy-support-1.4.0.jar//de.gerrygames.viarewind.legacysupport.injector.BoundingBoxFixer.fixLilyPad(BoundingBoxFixer.java:15)
[14:21:14 WARN]:        at viarewind-legacy-support-1.4.0.jar//de.gerrygames.viarewind.legacysupport.BukkitPlugin$1.run(BukkitPlugin.java:38)
[14:21:14 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101)
[14:21:14 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
[14:21:14 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1135)
[14:21:14 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316)
[14:21:14 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)
[14:21:14 INFO]: [ViaRewind-Legacy-Support] [STDOUT] Could not fix lily pad bounding box.
[14:21:14 WARN]: Nag author(s): '[Gerrygames]' of 'ViaRewind-Legacy-Support' about their usage of System.out/err.print. Please use your plugin's logger instead (JavaPlugin#getLogger).
[14:21:14 WARN]: java.lang.NullPointerException: Cannot invoke "java.lang.Class.getName()" because "clazz" is null
[14:21:14 WARN]:        at viarewind-legacy-support-1.4.0.jar//de.gerrygames.viarewind.legacysupport.reflection.ReflectionAPI.getField(ReflectionAPI.java:27)
[14:21:14 WARN]:        at viarewind-legacy-support-1.4.0.jar//de.gerrygames.viarewind.legacysupport.reflection.ReflectionAPI.getFieldAccessible(ReflectionAPI.java:45)
[14:21:14 WARN]:        at viarewind-legacy-support-1.4.0.jar//de.gerrygames.viarewind.legacysupport.injector.BoundingBoxFixer.fixLilyPad(BoundingBoxFixer.java:16)
[14:21:14 WARN]:        at viarewind-legacy-support-1.4.0.jar//de.gerrygames.viarewind.legacysupport.BukkitPlugin$1.run(BukkitPlugin.java:38)
[14:21:14 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101)
[14:21:14 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
[14:21:14 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1135)
[14:21:14 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316)
[14:21:14 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)
[14:21:14 WARN]: java.lang.ClassNotFoundException: net.minecraft.server.v1_17_R1.BlockLadder
[14:21:14 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:146)
[14:21:14 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103)
[14:21:14 WARN]:        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
[14:21:14 WARN]:        at java.base/java.lang.Class.forName0(Native Method)
[14:21:14 WARN]:        at java.base/java.lang.Class.forName(Class.java:375)
[14:21:14 WARN]:        at viarewind-legacy-support-1.4.0.jar//de.gerrygames.viarewind.legacysupport.injector.NMSReflection.getNMSClass(NMSReflection.java:15)
[14:21:14 WARN]:        at viarewind-legacy-support-1.4.0.jar//de.gerrygames.viarewind.legacysupport.injector.BoundingBoxFixer.fixLadder(BoundingBoxFixer.java:26)
[14:21:14 WARN]:        at viarewind-legacy-support-1.4.0.jar//de.gerrygames.viarewind.legacysupport.BukkitPlugin$1.run(BukkitPlugin.java:40)
[14:21:14 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101)
[14:21:14 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
[14:21:14 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1135)
[14:21:14 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316)
[14:21:14 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)
[14:21:14 INFO]: [ViaRewind-Legacy-Support] [STDOUT] Could not fix ladder bounding box.
[14:21:14 WARN]: Nag author(s): '[Gerrygames]' of 'ViaRewind-Legacy-Support' about their usage of System.out/err.print. Please use your plugin's logger instead (JavaPlugin#getLogger).
[14:21:14 WARN]: java.lang.NullPointerException: Cannot invoke "java.lang.Class.getName()" because "clazz" is null
[14:21:14 WARN]:        at viarewind-legacy-support-1.4.0.jar//de.gerrygames.viarewind.legacysupport.reflection.ReflectionAPI.getField(ReflectionAPI.java:27)
[14:21:14 WARN]:        at viarewind-legacy-support-1.4.0.jar//de.gerrygames.viarewind.legacysupport.reflection.ReflectionAPI.getFieldAccessible(ReflectionAPI.java:45)
[14:21:14 WARN]:        at viarewind-legacy-support-1.4.0.jar//de.gerrygames.viarewind.legacysupport.injector.BoundingBoxFixer.fixLadder(BoundingBoxFixer.java:42)
[14:21:14 WARN]:        at viarewind-legacy-support-1.4.0.jar//de.gerrygames.viarewind.legacysupport.BukkitPlugin$1.run(BukkitPlugin.java:40)
[14:21:14 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101)
[14:21:14 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
[14:21:14 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1135)
[14:21:14 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316)
[14:21:14 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)
[14:21:14 INFO]: [ViaVersion] Finished mapping loading, shutting down loader executor!
```

**Comment by LeehamElectronics** [comment]
The plugin says to "Nag" @Gerrygames  😂

**Comment by Camotoy** [comment]
The error about bounding boxes should be fixed with the latest source code. However, the Spigot release has not been updated to support this.
This message: `Nag author(s): '[Gerrygames]' of 'ViaRewind-Legacy-Support' about their usage of System.out/err.print.` doesn't quite make sense on initial glance as the code is definitely using the Bukkit logger: https://github.com/ViaVersion/ViaRewind-Legacy-Support/blob/master/src/main/java/de/gerrygames/viarewind/legacysupport/injector/BoundingBoxFixer.java#L25

**Comment by Jo0001** [comment]
Use the CI builds
ViaVersion - https://ci.viaversion.com/job/ViaVersion/lastSuccessfulBuild/artifact/build/libs/ViaVersion-4.0.2-SNAPSHOT.jar
ViaBackwards - https://ci.viaversion.com/job/ViaBackwards/lastSuccessfulBuild/artifact/build/libs/ViaBackwards-4.0.2-SNAPSHOT.jar
ViaRewind - https://ci.viaversion.com/job/ViaRewind/lastSuccessfulBuild/artifact/all/target/ViaRewind-2.0.2-SNAPSHOT.jar
ViaRewind Legacy Support (Bukkit) - https://ci.viaversion.com/view/All/job/ViaRewind%20Legacy%20Support/lastSuccessfulBuild/artifact/target/viarewind-legacy-support-1.4.1.jar
