### ISSUE TITLE
Issue with 1.8 on 1.17.1

### ISSUE THREAD

**Issue by OpenSource03** [ViaVersion/ViaRewind-Legacy-Support#34]
Hello there!

Currently, when placing any block on 1.8.8 client while server is 1.17+ (Java 16) with ViaBackwards, ViaRewind, ViaVersion (or all of their dev branches), as well as ViaRewind-Legacy-Support, the following error pops up:

```
[17:46:53 WARN]: java.lang.NullPointerException: Cannot invoke "java.lang.Class.getConstructor(java.lang.Class[])" because "blockPositionClass" is null
[17:46:53 WARN]:        at viarewind-legacy-support-1.4.0.jar//de.gerrygames.viarewind.legacysupport.listener.SoundListener.playBlockPlaceSound(SoundListener.java:97)
[17:46:53 WARN]:        at viarewind-legacy-support-1.4.0.jar//de.gerrygames.viarewind.legacysupport.listener.SoundListener.onBlockPlace(SoundListener.java:61)
[17:46:53 WARN]:        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor443.execute(Unknown Source)
[17:46:53 WARN]:        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
[17:46:53 WARN]:        at org.bukkit.plugin.EventExecutor$$Lambda$5564/0x000000008a215ce0.execute(Unknown Source)
[17:46:53 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[17:46:53 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[17:46:53 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624)
[17:46:53 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.callBlockPlaceEvent(CraftEventFactory.java:391)
[17:46:53 WARN]:        at net.minecraft.world.item.ItemStack.placeItem(ItemStack.java:372)
[17:46:53 WARN]:        at net.minecraft.server.level.PlayerInteractManager.a(PlayerInteractManager.java:603)
[17:46:53 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1882)
[17:46:53 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInUseItem.a(PacketPlayInUseItem.java:33)
[17:46:53 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInUseItem.a(PacketPlayInUseItem.java:9)
[17:46:53 WARN]:        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:56)
[17:46:53 WARN]:        at net.minecraft.network.protocol.PlayerConnectionUtils$$Lambda$8367/0x000000008a0638d8.run(Unknown Source)
[17:46:53 WARN]:        at net.minecraft.server.TickTask.run(TickTask.java:18)
[17:46:53 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:149)
[17:46:53 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.executeTask(IAsyncTaskHandlerReentrant.java:23)
[17:46:53 WARN]:        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:1433)
[17:46:53 WARN]:        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:192)
[17:46:53 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:122)
[17:46:53 WARN]:        at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1411)
[17:46:53 WARN]:        at net.minecraft.server.MinecraftServer.executeNext(MinecraftServer.java:1404)
[17:46:53 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:132)
[17:46:53 WARN]:        at net.minecraft.server.MinecraftServer.sleepForTick(MinecraftServer.java:1382)
[17:46:53 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1293)
[17:46:53 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321)
[17:46:53 WARN]:        at net.minecraft.server.MinecraftServer$$Lambda$3709/0x0000000093bc5018.run(Unknown Source)
[17:46:53 WARN]:        at java.base/java.lang.Thread.run(Thread.java:883)
```

**Comment by Jo0001** [comment]
I can't reproduce this with latest paper 1.17 and latest Via* from the ci (master branch).

**Comment by soshimee** [comment]
Well I can, and many issues talk about this.

**Comment by Jake4-CX** [comment]
> I can't reproduce this with latest paper 1.17 and latest Via* from the ci (master branch).

This also happens on a 1.16.5 Paper Server whilst using a 1.8 client (Latest ViaVersion)
