### ISSUE TITLE
Missing support for 1.18

### ISSUE THREAD

**Issue by PierreSchwang** [ViaVersion/ViaRewind-Legacy-Support#38]
1.18 support is missing, a NSME is thrown on block place:

https://cdn.discordapp.com/attachments/316208160232701955/922267635025059841/unknown.png

@ https://github.com/ViaVersion/ViaRewind-Legacy-Support/blob/master/src/main/java/de/gerrygames/viarewind/legacysupport/listener/SoundListener.java#L101

The called World#getType(BlockPosition) does not exists in nms code in 1.18

**Comment by MedicOP** [comment]
same problem on paper 1.18
```java
[21:29:34 WARN]: java.lang.NoSuchMethodException: net.minecraft.world.level.World.getType(net.minecraft.core.BlockPosition)
[21:29:34 WARN]:        at java.base/java.lang.Class.getMethod(Class.java:2227)
[21:29:34 WARN]:        at ViaRewind-Legacy-Support.jar//de.gerrygames.viarewind.legacysupport.listener.SoundListener.playBlockPlaceSound(SoundListener.java:101)
[21:29:34 WARN]:        at ViaRewind-Legacy-Support.jar//de.gerrygames.viarewind.legacysupport.listener.SoundListener.onBlockPlace(SoundListener.java:61)
[21:29:34 WARN]:        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor498.execute(Unknown Source)
[21:29:34 WARN]:        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75)
[21:29:34 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[21:29:34 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[21:29:34 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628)
[21:29:34 WARN]:        at org.bukkit.craftbukkit.v1_18_R1.event.CraftEventFactory.callBlockPlaceEvent(CraftEventFactory.java:392)
[21:29:34 WARN]:        at net.minecraft.world.item.ItemStack.useOn(ItemStack.java:373)
[21:29:34 WARN]:        at net.minecraft.server.level.PlayerInteractManager.a(PlayerInteractManager.java:599)
[21:29:34 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1838)
[21:29:34 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInUseItem.a(PacketPlayInUseItem.java:33)
[21:29:34 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInUseItem.a(PacketPlayInUseItem.java:9)
[21:29:34 WARN]:        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:56)
[21:29:34 WARN]:        at net.minecraft.server.TickTask.run(TickTask.java:18)
[21:29:34 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:149)
[21:29:34 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.c(IAsyncTaskHandlerReentrant.java:23)
[21:29:34 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1413)
[21:29:34 WARN]:        at net.minecraft.server.MinecraftServer.c(MinecraftServer.java:189)
[21:29:34 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.y(IAsyncTaskHandler.java:122)
[21:29:34 WARN]:        at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1391)
[21:29:34 WARN]:        at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1384)
[21:29:34 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:132)
[21:29:34 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1362)
[21:29:34 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1268)
[21:29:34 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
[21:29:34 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)```

**Comment by soshimee** [comment]
Same, I have a console spam as well. Everything doesn't work, not just block placements.

**Comment by soshimee** [comment]
Can confirm.
