### ISSUE TITLE
Error when block gets placed - Paper Spigot 1.16.5 - Client 1.8.8

### ISSUE THREAD

**Issue by Jake4-CX** [ViaVersion/ViaRewind-Legacy-Support#42]
Hello, whenever a player attempts (or places) a block on my server the console displays this (Figure 1.1). No sound is played on the client whereas later MC versions - I.e. 1.16.5 has sound without an error message.

Server: Paper Spigot 1.16.5
Java Version: 16
Client: Any 1.8 client

**I am using the latest version of Legacy Support as-well as the three other Via Version plugins.**

Figure 1.1 - Error Message:
```
java.lang.RuntimeException: Failed to resolve method in class java.lang.Boolean using [MethodSignature[name='getBlock', parameterTypes=[]], MethodSignature[name='b', parameterTypes=[]]]
        at de.gerrygames.viarewind.legacysupport.reflection.ReflectionAPI.pickMethod(ReflectionAPI.java:52)
        at de.gerrygames.viarewind.legacysupport.listener.SoundListener.playBlockPlaceSound(SoundListener.java:109)
        at de.gerrygames.viarewind.legacysupport.listener.SoundListener.onBlockPlace(SoundListener.java:63)
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1494.execute(Unknown Source)
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624)
        at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callBlockPlaceEvent(CraftEventFactory.java:398)
        at net.minecraft.server.v1_16_R3.ItemStack.placeItem(ItemStack.java:335)
        at net.minecraft.server.v1_16_R3.PlayerInteractManager.a(PlayerInteractManager.java:562)
        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1714)
        at net.minecraft.server.v1_16_R3.PacketPlayInUseItem.a(PacketPlayInUseItem.java:32)
        at net.minecraft.server.v1_16_R3.PacketPlayInUseItem.a(PacketPlayInUseItem.java:10)
        at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:35)
        at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18)
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
        at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1271)
        at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1264)
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119)
        at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1225)
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1139)
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291)
        at java.base/java.lang.Thread.run(Thread.java:831)
```

In addition to this (since it may help), The [jar](https://github.com/ViaVersion/ViaRewind-Legacy-Support/issues/12) that @codergautam provided in a previous Issue ticket had this issue fixed, but the main functions of Legacy Support do not work (Outdated).

**Comment by Jo0001** [comment]
Also happens with latest ViaRewind-Legacy-Support CI build (https://dump.viaversion.com/fb2664c7ca617b6129a3db244281cb5984e43e9b6eb0dcf92d871a79cd3c45d9)

**Comment by Jo0001** [comment]
Workaround is to use the old 1.4.0 (from https://www.spigotmc.org/resources/viarewind-legacy-support.52924/) , further things will be tracked in #50
