### ISSUE TITLE
problem on 1.19

### ISSUE THREAD

**Issue by BockerPaiar845** [ViaVersion/ViaRewind-Legacy-Support#45]
[18:49:10] [Server thread/WARN]: java.lang.NoSuchMethodException: net.minecraft.network.protocol.game.PacketPlayOutNamedSoundEffect.<init>(net.minecraft.sounds.SoundEffect,net.minecraft.sounds.SoundCategory,double,double,double,float,float)
[18:49:10] [Server thread/WARN]: 	at java.base/java.lang.Class.getConstructor0(Class.java:3585)
[18:49:10] [Server thread/WARN]: 	at java.base/java.lang.Class.getConstructor(Class.java:2271)
[18:49:10] [Server thread/WARN]: 	at viarewind-legacy-support-1.4.2-SNAPSHOT.jar//de.gerrygames.viarewind.legacysupport.listener.SoundListener.playSound(SoundListener.java:161)
[18:49:10] [Server thread/WARN]: 	at viarewind-legacy-support-1.4.2-SNAPSHOT.jar//de.gerrygames.viarewind.legacysupport.listener.SoundListener.playBlockPlaceSound(SoundListener.java:153)
[18:49:10] [Server thread/WARN]: 	at viarewind-legacy-support-1.4.2-SNAPSHOT.jar//de.gerrygames.viarewind.legacysupport.listener.SoundListener.onBlockPlace(SoundListener.java:63)
[18:49:10] [Server thread/WARN]: 	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor42.execute(Unknown Source)
[18:49:10] [Server thread/WARN]: 	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75)
[18:49:10] [Server thread/WARN]: 	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76)
[18:49:10] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[18:49:10] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:666)
[18:49:10] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_19_R1.event.CraftEventFactory.callBlockPlaceEvent(CraftEventFactory.java:393)
[18:49:10] [Server thread/WARN]: 	at net.minecraft.world.item.ItemStack.useOn(ItemStack.java:395)
[18:49:10] [Server thread/WARN]: 	at net.minecraft.server.level.PlayerInteractManager.a(PlayerInteractManager.java:588)
[18:49:10] [Server thread/WARN]: 	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1945)
[18:49:10] [Server thread/WARN]: 	at net.minecraft.network.protocol.game.PacketPlayInUseItem.a(PacketPlayInUseItem.java:37)
[18:49:10] [Server thread/WARN]: 	at net.minecraft.network.protocol.game.PacketPlayInUseItem.a(PacketPlayInUseItem.java:9)
[18:49:10] [Server thread/WARN]: 	at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:51)
[18:49:10] [Server thread/WARN]: 	at net.minecraft.server.TickTask.run(TickTask.java:18)
[18:49:10] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
[18:49:10] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
[18:49:10] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1385)
[18:49:10] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:183)
[18:49:10] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:126)
[18:49:10] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.bh(MinecraftServer.java:1362)
[18:49:10] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1355)
[18:49:10] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
[18:49:10] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1333)
[18:49:10] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1218)
[18:49:10] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:307)
[18:49:10] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
This error on my console

**Comment by Jo0001** [comment]
Also happens with latest ViaRewind-Legacy-Support CI build (https://dump.viaversion.com/c370ea1e1eb62fc5b0b572268ea7a3ba1afcf5de5bb7872a04d6b54a8c21e1d2)

**Comment by DominikSLK** [comment]
Fix in #48
