### ISSUE TITLE
1.12 servers crashing

### ISSUE THREAD

**Issue by FinnChildress** [ViaVersion/ViaRewind-Legacy-Support#46]
Build: https://ci.viaversion.com/view/All/job/ViaRewind%20Legacy%20Support/

My multiple 1.12 servers keep crashing after a few hours with this exception. Downgrading to the build from spigotmc.org fixes it:

```java.lang.NullPointerException: null
[02:34:59] [Server thread/WARN]: java.lang.NullPointerException
[02:34:59] [Server thread/WARN]: 	at de.gerrygames.viarewind.legacysupport.listener.SoundListener.playBlockPlaceSound(SoundListener.java:136)
[02:34:59] [Server thread/WARN]: 	at de.gerrygames.viarewind.legacysupport.listener.SoundListener.onBlockPlace(SoundListener.java:63)
[02:34:59] [Server thread/WARN]: 	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor746.execute(Unknown Source)
[02:34:59] [Server thread/WARN]: 	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70)
[02:34:59] [Server thread/WARN]: 	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78)
[02:34:59] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[02:34:59] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513)
[02:34:59] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callBlockPlaceEvent(CraftEventFactory.java:151)
[02:34:59] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.ItemStack.placeItem(ItemStack.java:234)
[02:34:59] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PlayerInteractManager.a(PlayerInteractManager.java:551)
[02:34:59] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1011)
[02:34:59] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:37)
[02:34:59] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:5)
[02:34:59] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14)
[02:34:59] [Server thread/WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[02:34:59] [Server thread/WARN]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[02:34:59] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)
[02:34:59] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:850)
[02:34:59] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423)
[02:34:59] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774)
[02:34:59] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666)
[02:34:59] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[02:34:59] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.server.v1_12_R1.ReportedException: Ticking player
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:932) ~[patched_1.12.2.jar:git-Paper-"77cce8236"]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[patched_1.12.2.jar:git-Paper-"77cce8236"]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774) ~[patched_1.12.2.jar:git-Paper-"77cce8236"]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666) ~[patched_1.12.2.jar:git-Paper-"77cce8236"]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]
Caused by: java.lang.NullPointerException
	at net.minecraft.server.v1_12_R1.ItemStack.usesData(ItemStack.java:363) ~[patched_1.12.2.jar:git-Paper-"77cce8236"]
	at net.minecraft.server.v1_12_R1.ItemStack.setData(ItemStack.java:391) ~[patched_1.12.2.jar:git-Paper-"77cce8236"]
	at net.minecraft.server.v1_12_R1.ItemStack.<init>(ItemStack.java:87) ~[patched_1.12.2.jar:git-Paper-"77cce8236"]
	at net.minecraft.server.v1_12_R1.ItemStack.cloneItemStack(ItemStack.java:503) ~[patched_1.12.2.jar:git-Paper-"77cce8236"]
	at net.minecraft.server.v1_12_R1.PacketPlayOutSetSlot.<init>(SourceFile:25) ~[patched_1.12.2.jar:git-Paper-"77cce8236"]
	at net.minecraft.server.v1_12_R1.EntityPlayer.a(EntityPlayer.java:964) ~[patched_1.12.2.jar:git-Paper-"77cce8236"]
	at net.minecraft.server.v1_12_R1.Container.b(Container.java:84) ~[patched_1.12.2.jar:git-Paper-"77cce8236"]
	at net.minecraft.server.v1_12_R1.EntityPlayer.B_(EntityPlayer.java:289) ~[patched_1.12.2.jar:git-Paper-"77cce8236"]
	at net.minecraft.server.v1_12_R1.World.entityJoinedWorld(World.java:1797) ~[patched_1.12.2.jar:git-Paper-"77cce8236"]
	at net.minecraft.server.v1_12_R1.World.h(World.java:1767) ~[patched_1.12.2.jar:git-Paper-"77cce8236"]
	at net.minecraft.server.v1_12_R1.WorldServer.l(WorldServer.java:705) ~[patched_1.12.2.jar:git-Paper-"77cce8236"]
	at net.minecraft.server.v1_12_R1.World.tickEntities(World.java:1540) ~[patched_1.12.2.jar:git-Paper-"77cce8236"]
	at net.minecraft.server.v1_12_R1.WorldServer.tickEntities(WorldServer.java:682) ~[patched_1.12.2.jar:git-Paper-"77cce8236"]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:921) ~[patched_1.12.2.jar:git-Paper-"77cce8236"]
	... 4 more
[02:34:59] [Server thread/ERROR]: 	Cause of unexpected exception was
java.lang.NullPointerException: null
	at net.minecraft.server.v1_12_R1.ItemStack.usesData(ItemStack.java:363) ~[patched_1.12.2.jar:git-Paper-"77cce8236"]
	at net.minecraft.server.v1_12_R1.ItemStack.setData(ItemStack.java:391) ~[patched_1.12.2.jar:git-Paper-"77cce8236"]
	at net.minecraft.server.v1_12_R1.ItemStack.<init>(ItemStack.java:87) ~[patched_1.12.2.jar:git-Paper-"77cce8236"]
	at net.minecraft.server.v1_12_R1.ItemStack.cloneItemStack(ItemStack.java:503) ~[patched_1.12.2.jar:git-Paper-"77cce8236"]
	at net.minecraft.server.v1_12_R1.PacketPlayOutSetSlot.<init>(SourceFile:25) ~[patched_1.12.2.jar:git-Paper-"77cce8236"]
	at net.minecraft.server.v1_12_R1.EntityPlayer.a(EntityPlayer.java:964) ~[patched_1.12.2.jar:git-Paper-"77cce8236"]
	at net.minecraft.server.v1_12_R1.Container.b(Container.java:84) ~[patched_1.12.2.jar:git-Paper-"77cce8236"]
	at net.minecraft.server.v1_12_R1.EntityPlayer.B_(EntityPlayer.java:289) ~[patched_1.12.2.jar:git-Paper-"77cce8236"]
	at net.minecraft.server.v1_12_R1.World.entityJoinedWorld(World.java:1797) ~[patched_1.12.2.jar:git-Paper-"77cce8236"]
	at net.minecraft.server.v1_12_R1.World.h(World.java:1767) ~[patched_1.12.2.jar:git-Paper-"77cce8236"]
	at net.minecraft.server.v1_12_R1.WorldServer.l(WorldServer.java:705) ~[patched_1.12.2.jar:git-Paper-"77cce8236"]
	at net.minecraft.server.v1_12_R1.World.tickEntities(World.java:1540) ~[patched_1.12.2.jar:git-Paper-"77cce8236"]
	at net.minecraft.server.v1_12_R1.WorldServer.tickEntities(WorldServer.java:682) ~[patched_1.12.2.jar:git-Paper-"77cce8236"]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:921) ~[patched_1.12.2.jar:git-Paper-"77cce8236"]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[patched_1.12.2.jar:git-Paper-"77cce8236"]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774) ~[patched_1.12.2.jar:git-Paper-"77cce8236"]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666) ~[patched_1.12.2.jar:git-Paper-"77cce8236"]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]
[02:34:59] [Server thread/ERROR]: This crash report has been saved to: /home/minecraft/multicraft/servers/XXXX/./crash-reports/crash-2022-06-29_02.34.59-server.txt
[02:34:59] [Server thread/INFO]: Stopping server

**Comment by HowardZHY** [comment]
u need a dump
/viaversion dump

**Comment by qaz197418i** [comment]
My server version 1.12.2, has same crash too

**Comment by SissioMisio** [comment]
Same exact problem: 1.12.2, 1.8 client causes a crash when placing blocks and/or dying in the void.

**Comment by FlorianMichael** [comment]
Fixed in latest master commit
