### ISSUE TITLE
Cannot invoke "Object.getClass()" because "soundType" is null

### ISSUE THREAD

**Issue by Schnell1337** [ViaVersion/ViaRewind-Legacy-Support#55]
When I use boat in minecraft client version 1.8, I get something like this: https://www.youtube.com/watch?v=7jNjXTXRV9o

Error in the console: https://pastebin.com/VCn6WmVR

For example, when you use 1.12.2 and above, everything is fine

Server version: paper 1.12.2

Latest version of ViaRewind Legacy Support: 1.4.2

**Comment by skbeh** [comment]
It has the same problem with 1.12.2.
```console
[13:13:23 WARN]: java.lang.NullPointerException: Cannot invoke "Object.getClass()" because "soundType" is null
[13:13:23 WARN]:        at de.gerrygames.viarewind.legacysupport.listener.SoundListener.playBlockPlaceSound(SoundListener.java:140)
[13:13:23 WARN]:        at de.gerrygames.viarewind.legacysupport.listener.SoundListener.onBlockPlace(SoundListener.java:67)
[13:13:23 WARN]:        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor80.execute(Unknown Source)
[13:13:23 WARN]:        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70)
[13:13:23 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78)
[13:13:23 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[13:13:23 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513)
[13:13:23 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callBlockPlaceEvent(CraftEventFactory.java:151)
[13:13:23 WARN]:        at net.minecraft.server.v1_12_R1.ItemStack.placeItem(ItemStack.java:234)
[13:13:23 WARN]:        at net.minecraft.server.v1_12_R1.PlayerInteractManager.a(PlayerInteractManager.java:558)
[13:13:23 WARN]:        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1025)
[13:13:23 WARN]:        at net.minecraft.server.v1_12_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:37)
[13:13:23 WARN]:        at net.minecraft.server.v1_12_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:5)
[13:13:23 WARN]:        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14)
[13:13:23 WARN]:        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:577)
[13:13:23 WARN]:        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
[13:13:23 WARN]:        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)
[13:13:23 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:851)
[13:13:23 WARN]:        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:427)
[13:13:23 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:775)
[13:13:23 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666)
[13:13:23 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1589)
[13:13:23 ERROR]: Encountered an unexpected exception
net.minecraft.server.v1_12_R1.ReportedException: Ticking player
at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:944) ~[patched_1.12.2.jar:git-Dionysus-"42ce9ca"]
at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:427) ~[patched_1.12.2.jar:git-Dionysus-"42ce9ca"]
at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:775) ~[patched_1.12.2.jar:git-Dionysus-"42ce9ca"]
at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666) ~[patched_1.12.2.jar:git-Dionysus-"42ce9ca"]
at java.lang.Thread.run(Thread.java:1589) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraft.server.v1_12_R1.Item.k()" because the return value of "net.minecraft.server.v1_12_R1.ItemStack.getItem()" is null
at net.minecraft.server.v1_12_R1.ItemStack.usesData(ItemStack.java:363) ~[patched_1.12.2.jar:git-Dionysus-"42ce9ca"]
at net.minecraft.server.v1_12_R1.ItemStack.setData(ItemStack.java:391) ~[patched_1.12.2.jar:git-Dionysus-"42ce9ca"]
at net.minecraft.server.v1_12_R1.ItemStack.<init>(ItemStack.java:87) ~[patched_1.12.2.jar:git-Dionysus-"42ce9ca"]
at net.minecraft.server.v1_12_R1.ItemStack.cloneItemStack(ItemStack.java:503) ~[patched_1.12.2.jar:git-Dionysus-"42ce9ca"]
at net.minecraft.server.v1_12_R1.PacketPlayOutSetSlot.<init>(SourceFile:25) ~[patched_1.12.2.jar:git-Dionysus-"42ce9ca"]
at net.minecraft.server.v1_12_R1.EntityPlayer.a(EntityPlayer.java:969) ~[patched_1.12.2.jar:git-Dionysus-"42ce9ca"]
at net.minecraft.server.v1_12_R1.Container.b(Container.java:84) ~[patched_1.12.2.jar:git-Dionysus-"42ce9ca"]
at net.minecraft.server.v1_12_R1.EntityPlayer.B_(EntityPlayer.java:294) ~[patched_1.12.2.jar:git-Dionysus-"42ce9ca"]
at net.minecraft.server.v1_12_R1.World.entityJoinedWorld(World.java:1793) ~[patched_1.12.2.jar:git-Dionysus-"42ce9ca"]
at net.minecraft.server.v1_12_R1.World.h(World.java:1763) ~[patched_1.12.2.jar:git-Dionysus-"42ce9ca"]
at net.minecraft.server.v1_12_R1.WorldServer.l(WorldServer.java:690) ~[patched_1.12.2.jar:git-Dionysus-"42ce9ca"]
at net.minecraft.server.v1_12_R1.World.tickEntities(World.java:1536) ~[patched_1.12.2.jar:git-Dionysus-"42ce9ca"]
at net.minecraft.server.v1_12_R1.WorldServer.tickEntities(WorldServer.java:667) ~[patched_1.12.2.jar:git-Dionysus-"42ce9ca"]
at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:933) ~[patched_1.12.2.jar:git-Dionysus-"42ce9ca"]
... 4 more
[13:13:23 ERROR]:       Cause of unexpected exception was
java.lang.NullPointerException: Cannot invoke "net.minecraft.server.v1_12_R1.Item.k()" because the return value of "net.minecraft.server.v1_12_R1.ItemStack.getItem()" is null
at net.minecraft.server.v1_12_R1.ItemStack.usesData(ItemStack.java:363) ~[patched_1.12.2.jar:git-Dionysus-"42ce9ca"]
at net.minecraft.server.v1_12_R1.ItemStack.setData(ItemStack.java:391) ~[patched_1.12.2.jar:git-Dionysus-"42ce9ca"]
at net.minecraft.server.v1_12_R1.ItemStack.<init>(ItemStack.java:87) ~[patched_1.12.2.jar:git-Dionysus-"42ce9ca"]
at net.minecraft.server.v1_12_R1.ItemStack.cloneItemStack(ItemStack.java:503) ~[patched_1.12.2.jar:git-Dionysus-"42ce9ca"]
at net.minecraft.server.v1_12_R1.PacketPlayOutSetSlot.<init>(SourceFile:25) ~[patched_1.12.2.jar:git-Dionysus-"42ce9ca"]
at net.minecraft.server.v1_12_R1.EntityPlayer.a(EntityPlayer.java:969) ~[patched_1.12.2.jar:git-Dionysus-"42ce9ca"]
at net.minecraft.server.v1_12_R1.Container.b(Container.java:84) ~[patched_1.12.2.jar:git-Dionysus-"42ce9ca"]
at net.minecraft.server.v1_12_R1.EntityPlayer.B_(EntityPlayer.java:294) ~[patched_1.12.2.jar:git-Dionysus-"42ce9ca"]
at net.minecraft.server.v1_12_R1.World.entityJoinedWorld(World.java:1793) ~[patched_1.12.2.jar:git-Dionysus-"42ce9ca"]
at net.minecraft.server.v1_12_R1.World.h(World.java:1763) ~[patched_1.12.2.jar:git-Dionysus-"42ce9ca"]
at net.minecraft.server.v1_12_R1.WorldServer.l(WorldServer.java:690) ~[patched_1.12.2.jar:git-Dionysus-"42ce9ca"]
at net.minecraft.server.v1_12_R1.World.tickEntities(World.java:1536) ~[patched_1.12.2.jar:git-Dionysus-"42ce9ca"]
at net.minecraft.server.v1_12_R1.WorldServer.tickEntities(WorldServer.java:667) ~[patched_1.12.2.jar:git-Dionysus-"42ce9ca"]
at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:933) ~[patched_1.12.2.jar:git-Dionysus-"42ce9ca"]
at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:427) ~[patched_1.12.2.jar:git-Dionysus-"42ce9ca"]
at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:775) ~[patched_1.12.2.jar:git-Dionysus-"42ce9ca"]
at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666) ~[patched_1.12.2.jar:git-Dionysus-"42ce9ca"]
at java.lang.Thread.run(Thread.java:1589) ~[?:?]
```

**Comment by HowardZHY** [comment]
Did you use latest ViaRewind from Jenkins?

**Comment by skbeh** [comment]
@HowardZHY I am using ViaRewind@49e72d487cf0ea5e747dbf109c4c1efd70a046a2.

**Comment by SissioMisio** [comment]
Same exact problem. This seems to lead to a crash.
Server: Paper 1.12.2
Client: 1.8.x
ViaRewind-Legacy-Support 1.5.0-SNAPSHOT+2

**Comment by FlorianMichael** [comment]
Fixed in latest master commit
