### ISSUE TITLE
Error with ViaVersion

### ISSUE THREAD

**Issue by Rap3erka** [ViaVersion/ViaRewind-Legacy-Support#65]
[10:14:41] [Netty Epoll Server IO #1/WARN]: [ViaVersion] ERROR IN Protocol1_20_2To1_20 IN REMAP OF JOIN_GAME (0x28)
[10:14:41] [Netty Epoll Server IO #1/WARN]: io.netty.handler.codec.EncoderException: com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository
[10:14:41] [Netty Epoll Server IO #1/WARN]: Source 0: com.viaversion.viaversion.protocols.protocol1_20_2to1_20.rewriter.EntityPacketRewriter1_20_2$1 (Anonymous)
[10:14:41] [Netty Epoll Server IO #1/WARN]: 	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:107)
[10:14:41] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[10:14:41] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[10:14:41] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[10:14:41] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[10:14:41] [Netty Epoll Server IO #1/WARN]: 	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:113)
[10:14:41] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[10:14:41] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[10:14:41] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[10:14:41] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[10:14:41] [Netty Epoll Server IO #1/WARN]: 	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:120)
[10:14:41] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[10:14:41] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[10:14:41] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[10:14:41] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[10:14:41] [Netty Epoll Server IO #1/WARN]: 	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:113)
[10:14:41] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[10:14:41] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:940)
[10:14:41] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:966)
[10:14:41] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:934)
[10:14:41] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1020)
[10:14:41] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:311)
[10:14:41] [Netty Epoll Server IO #1/WARN]: 	at ProtocolLib (1).jar//com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.writeAndFlush(NettyChannelProxy.java:227)
[10:14:41] [Netty Epoll Server IO #1/WARN]: 	at ProtocolLib (1).jar//com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.writeAndFlush(NettyChannelProxy.java:233)
[10:14:41] [Netty Epoll Server IO #1/WARN]: 	at net.minecraft.network.NetworkManager.doSendPacket(NetworkManager.java:476)
[10:14:41] [Netty Epoll Server IO #1/WARN]: 	at net.minecraft.network.NetworkManager.lambda$sendPacket$11(NetworkManager.java:450)
[10:14:41] [Netty Epoll Server IO #1/WARN]: 	at ProtocolLib (1).jar//com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.lambda$proxyRunnable$2(NettyEventLoopProxy.java:48)
[10:14:41] [Netty Epoll Server IO #1/WARN]: 	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
[10:14:41] [Netty Epoll Server IO #1/WARN]: 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
[10:14:41] [Netty Epoll Server IO #1/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
[10:14:41] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:403)
[10:14:41] [Netty Epoll Server IO #1/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[10:14:41] [Netty Epoll Server IO #1/WARN]: 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[10:14:41] [Netty Epoll Server IO #1/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[10:14:41] [Netty Epoll Server IO #1/WARN]: Caused by: com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository
[10:14:41] [Netty Epoll Server IO #1/WARN]: Source 0: com.viaversion.viaversion.protocols.protocol1_20_2to1_20.rewriter.EntityPacketRewriter1_20_2$1 (Anonymous)
[10:14:41] [Netty Epoll Server IO #1/WARN]: Caused by: java.lang.NullPointerException: Cannot invoke "com.viaversion.viaversion.api.data.entity.EntityTracker.dimensionData(String)" because "tracker" is null
[10:14:41] [Netty Epoll Server IO #1/WARN]: 	at ViaVersion-4.8.1.jar//com.viaversion.viaversion.rewriter.EntityRewriter.lambda$worldDataTrackerHandlerByKey$6(EntityRewriter.java:454)
[10:14:41] [Netty Epoll Server IO #1/WARN]: 	at ViaVersion-4.8.1.jar//com.viaversion.viaversion.api.protocol.remapper.PacketHandlers.handle(PacketHandlers.java:158)
[10:14:41] [Netty Epoll Server IO #1/WARN]: 	at ViaVersion-4.8.1.jar//com.viaversion.viaversion.api.protocol.AbstractProtocol.transform(AbstractProtocol.java:392)
[10:14:41] [Netty Epoll Server IO #1/WARN]: 	at ViaVersion-4.8.1.jar//com.viaversion.viaversion.protocols.protocol1_20_2to1_20.Protocol1_20_2To1_20.transform(Protocol1_20_2To1_20.java:232)
[10:14:41] [Netty Epoll Server IO #1/WARN]: 	at ViaVersion-4.8.1.jar//com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:426)
[10:14:41] [Netty Epoll Server IO #1/WARN]: 	at ViaVersion-4.8.1.jar//com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:410)
[10:14:41] [Netty Epoll Server IO #1/WARN]: 	at ViaVersion-4.8.1.jar//com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:46)
[10:14:41] [Netty Epoll Server IO #1/WARN]: 	at ViaVersion-4.8.1.jar//com.viaversion.viaversion.protocol.ProtocolPipelineImpl.transform(ProtocolPipelineImpl.java:116)
[10:14:41] [Netty Epoll Server IO #1/WARN]: 	at ViaVersion-4.8.1.jar//com.viaversion.viaversion.connection.UserConnectionImpl.transform(UserConnectionImpl.java:330)
[10:14:41] [Netty Epoll Server IO #1/WARN]: 	at ViaVersion-4.8.1.jar//com.viaversion.viaversion.connection.UserConnectionImpl.transformClientbound(UserConnectionImpl.java:308)
[10:14:41] [Netty Epoll Server IO #1/WARN]: 	at ViaVersion-4.8.1.jar//com.viaversion.viaversion.bukkit.handlers.BukkitEncodeHandler.encode(BukkitEncodeHandler.java:57)
[10:14:41] [Netty Epoll Server IO #1/WARN]: 	at ViaVersion-4.8.1.jar//com.viaversion.viaversion.bukkit.handlers.BukkitEncodeHandler.encode(BukkitEncodeHandler.java:35)
[10:14:41] [Netty Epoll Server IO #1/WARN]: 	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:90)
[10:14:41] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[10:14:41] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[10:14:41] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[10:14:41] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[10:14:41] [Netty Epoll Server IO #1/WARN]: 	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:113)
[10:14:41] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[10:14:41] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[10:14:41] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[10:14:41] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[10:14:41] [Netty Epoll Server IO #1/WARN]: 	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:120)
[10:14:41] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[10:14:41] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[10:14:41] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[10:14:41] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[10:14:41] [Netty Epoll Server IO #1/WARN]: 	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:113)
[10:14:41] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[10:14:41] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:940)
[10:14:41] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:966)
[10:14:41] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:934)
[10:14:41] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1020)
[10:14:41] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:311)
[10:14:41] [Netty Epoll Server IO #1/WARN]: 	at ProtocolLib (1).jar//com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.writeAndFlush(NettyChannelProxy.java:227)
[10:14:41] [Netty Epoll Server IO #1/WARN]: 	at ProtocolLib (1).jar//com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.writeAndFlush(NettyChannelProxy.java:233)
[10:14:41] [Netty Epoll Server IO #1/WARN]: 	at net.minecraft.network.NetworkManager.doSendPacket(NetworkManager.java:476)
[10:14:41] [Netty Epoll Server IO #1/WARN]: 	at net.minecraft.network.NetworkManager.lambda$sendPacket$11(NetworkManager.java:450)
[10:14:41] [Netty Epoll Server IO #1/WARN]: 	at ProtocolLib (1).jar//com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.lambda$proxyRunnable$2(NettyEventLoopProxy.java:48)
[10:14:41] [Netty Epoll Server IO #1/WARN]: 	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
[10:14:41] [Netty Epoll Server IO #1/WARN]: 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
[10:14:41] [Netty Epoll Server IO #1/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
[10:14:41] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:403)
[10:14:41] [Netty Epoll Server IO #1/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[10:14:41] [Netty Epoll Server IO #1/WARN]: 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[10:14:41] [Netty Epoll Server IO #1/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by FlorianMichael** [comment]
Please report this issue on the ViaVersion repository. https://github.com/ViaVersion/ViaVersion
