### ISSUE TITLE
NullPointerException around playBlockPlaceSoundNMS method

### ISSUE THREAD

**Issue by TheJoshue** [ViaVersion/ViaRewind-Legacy-Support#70]
logs:
```
[12:35:17] [Server thread/WARN]: java.lang.NullPointerException
[12:35:17] [Server thread/WARN]: 	at com.viaversion.viarewind.legacysupport.listener.SoundListener.playBlockPlaceSoundNMS(SoundListener.java:165)
[12:35:17] [Server thread/WARN]: 	at com.viaversion.viarewind.legacysupport.listener.SoundListener.onBlockPlace(SoundListener.java:91)
[12:35:17] [Server thread/WARN]: 	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor683.execute(Unknown Source)
[12:35:17] [Server thread/WARN]: 	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70)
[12:35:17] [Server thread/WARN]: 	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78)
[12:35:17] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[12:35:17] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513)
[12:35:17] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callBlockPlaceEvent(CraftEventFactory.java:151)
[12:35:17] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.ItemStack.placeItem(ItemStack.java:234)
[12:35:17] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PlayerInteractManager.a(PlayerInteractManager.java:551)
[12:35:17] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1011)
[12:35:17] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:37)
[12:35:17] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:5)
[12:35:17] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14)
[12:35:17] [Server thread/WARN]: 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[12:35:17] [Server thread/WARN]: 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[12:35:17] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)
[12:35:17] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:850)
[12:35:17] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423)
[12:35:17] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774)
[12:35:17] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666)
[12:35:17] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:829)
[12:35:18] [Server thread/WARN]: java.lang.NullPointerException
[12:35:18] [Server thread/WARN]: 	at com.viaversion.viarewind.legacysupport.listener.SoundListener.playBlockPlaceSoundNMS(SoundListener.java:165)
[12:35:18] [Server thread/WARN]: 	at com.viaversion.viarewind.legacysupport.listener.SoundListener.onBlockPlace(SoundListener.java:91)
[12:35:18] [Server thread/WARN]: 	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor683.execute(Unknown Source)
[12:35:18] [Server thread/WARN]: 	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70)
[12:35:18] [Server thread/WARN]: 	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78)
[12:35:18] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[12:35:18] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513)
[12:35:18] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callBlockPlaceEvent(CraftEventFactory.java:151)
[12:35:18] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.ItemStack.placeItem(ItemStack.java:234)
[12:35:18] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PlayerInteractManager.a(PlayerInteractManager.java:551)
[12:35:18] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1011)
[12:35:18] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:37)
[12:35:18] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:5)
[12:35:18] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14)
[12:35:18] [Server thread/WARN]: 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[12:35:18] [Server thread/WARN]: 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[12:35:18] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)
[12:35:18] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:850)
[12:35:18] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423)
[12:35:18] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774)
[12:35:18] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666)
[12:35:18] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:829)
```

This started suddently happening on 1.12.2 server when i place block using 1.8.9 client

**Comment by FlorianMichael** [comment]
Fixed in latest master commit
