### ISSUE TITLE
Could not fix ladder bounding box.

### ISSUE THREAD

**Issue by Incluuu** [ViaVersion/ViaRewind-Legacy-Support#71]
On startup on purpur/paper 1.20.4

[13:29:10 ERROR]: [ViaRewind-Legacy-Support] Could not fix ladder bounding box.
java.lang.IllegalStateException: Unknown bounding box type: java.lang.Float
        at com.viaversion.viarewind.legacysupport.injector.BoundingBoxFixer.setBoundingBox(BoundingBoxFixer.java:94) ~[ViaRewind-Legacy-Support-1.5.0-SNAPSHOT.jar:?]
        at com.viaversion.viarewind.legacysupport.injector.BoundingBoxFixer.fixLadder(BoundingBoxFixer.java:68) ~[ViaRewind-Legacy-Support-1.5.0-SNAPSHOT.jar:?]
        at com.viaversion.viarewind.legacysupport.BukkitPlugin$1.run(BukkitPlugin.java:67) ~[ViaRewind-Legacy-Support-1.5.0-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.20.4.jar:git-Purpur-2110]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480) ~[purpur-1.20.4.jar:git-Purpur-2110]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1159) ~[purpur-1.20.4.jar:git-Purpur-2110]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:326) ~[purpur-1.20.4.jar:git-Purpur-2110]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[13:29:10 ERROR]: [ViaRewind-Legacy-Support] Could not fix lily pad bounding box.
java.lang.IllegalStateException: Unknown bounding box type: com.mojang.serialization.codecs.RecordCodecBuilder$2
        at com.viaversion.viarewind.legacysupport.injector.BoundingBoxFixer.setBoundingBox(BoundingBoxFixer.java:94) ~[ViaRewind-Legacy-Support-1.5.0-SNAPSHOT.jar:?]
        at com.viaversion.viarewind.legacysupport.injector.BoundingBoxFixer.fixLilyPad(BoundingBoxFixer.java:38) ~[ViaRewind-Legacy-Support-1.5.0-SNAPSHOT.jar:?]
        at com.viaversion.viarewind.legacysupport.BukkitPlugin$1.run(BukkitPlugin.java:83) ~[ViaRewind-Legacy-Support-1.5.0-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.20.4.jar:git-Purpur-2110]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480) ~[purpur-1.20.4.jar:git-Purpur-2110]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1159) ~[purpur-1.20.4.jar:git-Purpur-2110]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:326) ~[purpur-1.20.4.jar:git-Purpur-2110]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by FlorianMichael** [comment]
Should be fixed with latest ViaRewind Legacy Support, make sure to download the correct version depending on your other Via* plugins. (Make sure to not mixup dev and master versions)
