### ISSUE TITLE
Error spam

### ISSUE THREAD

**Issue by Atticuss26** [ViaVersion/ViaRewind-Legacy-Support#75]
Latest snapshot and 1.17: 
23:35:58 WARN]: [ViaRewind-Legacy-Support] Task #30 for ViaRewind-Legacy-Support v1.5.0-SNAPSHOT generated an exception
java.lang.NoSuchMethodError: 'com.viaversion.viaversion.api.protocol.version.ProtocolVersion com.viaversion.viaversion.api.protocol.version.ServerProtocolVersion.lowestSupportedProtocolVersion()'
	at com.viaversion.viarewind.legacysupport.BukkitPlugin$1.run(BukkitPlugin.java:52) ~[ViaRewind-Legacy-Support-1.5.0-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Purpur-1428]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[patched_1.17.1.jar:git-Purpur-1428]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1591) ~[patched_1.17.1.jar:git-Purpur-1428]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:528) ~[patched_1.17.1.jar:git-Purpur-1428]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1507) ~[patched_1.17.1.jar:git-Purpur-1428]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1300) ~[patched_1.17.1.jar:git-Purpur-1428]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:322) ~[patched_1.17.1.jar:git-Purpur-1428]
	at java.lang.Thread.run(Thread.java:840) ~[?:?]

**Comment by FlorianMichael** [comment]
You can use this version now: https://hangar.papermc.io/ViaVersion/ViaRewindLegacySupport/versions/1.5.0-SNAPSHOT+10
