### ISSUE TITLE
console spam on place block paper 1.12.2

### ISSUE THREAD

**Issue by Incluuu** [ViaVersion/ViaRewind-Legacy-Support#77]
19:37:12 WARN]: java.lang.NullPointerException
[19:37:12 WARN]:        at com.viaversion.viarewind.legacysupport.util.NMSUtil.sendPacket(NMSUtil.java:101)
[19:37:12 WARN]:        at com.viaversion.viarewind.legacysupport.feature.BlockPlaceSoundEmulator.playSound(BlockPlaceSoundEmulator.java:212)
[19:37:12 WARN]:        at com.viaversion.viarewind.legacysupport.feature.BlockPlaceSoundEmulator.playBlockPlaceSoundNMS(BlockPlaceSoundEmulator.java:194)
[19:37:12 WARN]:        at com.viaversion.viarewind.legacysupport.feature.BlockPlaceSoundEmulator.onBlockPlace(BlockPlaceSoundEmulator.java:93)
[19:37:12 WARN]:        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor587.execute(Unknown Source)
[19:37:12 WARN]:        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70)
[19:37:12 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74)
[19:37:12 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[19:37:12 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513)
[19:37:12 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callBlockPlaceEvent(CraftEventFactory.java:151)
[19:37:12 WARN]:        at net.minecraft.server.v1_12_R1.ItemStack.placeItem(ItemStack.java:234)
[19:37:12 WARN]:        at net.minecraft.server.v1_12_R1.PlayerInteractManager.a(PlayerInteractManager.java:551)
[19:37:12 WARN]:        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1011)
[19:37:12 WARN]:        at net.minecraft.server.v1_12_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:37)
[19:37:12 WARN]:        at net.minecraft.server.v1_12_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:5)
[19:37:12 WARN]:        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14)
[19:37:12 WARN]:        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[19:37:12 WARN]:        at java.util.concurrent.FutureTask.run(Unknown Source)
[19:37:12 WARN]:        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)
[19:37:12 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:850)
[19:37:12 WARN]:        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423)
[19:37:12 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774)
[19:37:12 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666)
[19:37:12 WARN]:        at java.lang.Thread.run(Unknown Source)

**Comment by Incluuu** [comment]
Minecraft client version 1.8.8

**Comment by FlorianMichael** [comment]
Fixed, redownload latest snapshot from Hangar
