### ISSUE TITLE
Missing required data class org.bukkit.Color

### ISSUE THREAD

**Issue by IAISI** [ViaVersion/ViaRewind-Legacy-Support#81]
```
[13:05:47] [Server thread/WARN]: [ViaRewind-Legacy-Support] Task #3291 for ViaRewind-Legacy-Support v1.5.1 generated an exception
java.lang.IllegalArgumentException: missing required data class org.bukkit.Color
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:218) ~[guava-32.1.2-jre.jar:?]
	at org.bukkit.craftbukkit.CraftParticle.createParticleParam(CraftParticle.java:68) ~[sakura-1.20.6.jar:1.20.6-DEV-631307b]
	at org.bukkit.craftbukkit.entity.CraftPlayer.spawnParticle(CraftPlayer.java:2981) ~[sakura-1.20.6.jar:1.20.6-DEV-631307b]
	at org.bukkit.craftbukkit.entity.CraftPlayer.spawnParticle(CraftPlayer.java:2971) ~[sakura-1.20.6.jar:1.20.6-DEV-631307b]
	at org.bukkit.craftbukkit.entity.CraftPlayer.spawnParticle(CraftPlayer.java:2951) ~[sakura-1.20.6.jar:1.20.6-DEV-631307b]
	at org.bukkit.craftbukkit.entity.CraftPlayer.spawnParticle(CraftPlayer.java:2941) ~[sakura-1.20.6.jar:1.20.6-DEV-631307b]
	at ViaRewind-Legacy-Support.jar/com.viaversion.viarewind.legacysupport.feature.AreaEffectCloudEmulator.lambda$new$3(AreaEffectCloudEmulator.java:66) ~[ViaRewind-Legacy-Support.jar:?]
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) ~[?:?]
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?]
	at java.base/java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1715) ~[?:?]
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[?:?]
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[?:?]
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
	at ViaRewind-Legacy-Support.jar/com.viaversion.viarewind.legacysupport.feature.AreaEffectCloudEmulator.lambda$new$4(AreaEffectCloudEmulator.java:64) ~[ViaRewind-Legacy-Support.jar:?]
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596) ~[?:?]
	at ViaRewind-Legacy-Support.jar/com.viaversion.viarewind.legacysupport.feature.AreaEffectCloudEmulator.lambda$new$5(AreaEffectCloudEmulator.java:45) ~[ViaRewind-Legacy-Support.jar:?]
	at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:101) ~[sakura-1.20.6.jar:1.20.6-DEV-631307b]
	at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:482) ~[sakura-1.20.6.jar:1.20.6-DEV-631307b]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1707) ~[sakura-1.20.6.jar:1.20.6-DEV-631307b]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:472) ~[sakura-1.20.6.jar:1.20.6-DEV-631307b]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1579) ~[sakura-1.20.6.jar:1.20.6-DEV-631307b]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1238) ~[sakura-1.20.6.jar:1.20.6-DEV-631307b]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:324) ~[sakura-1.20.6.jar:1.20.6-DEV-631307b]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
[13:05:47] [Server thread/WARN]: com.destroystokyo.paper.exception.ServerSchedulerException: Task #3291 for ViaRewind-Legacy-Support v1.5.1 generated an exception
[13:05:47] [Server thread/WARN]: 	at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:497)
[13:05:47] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1707)
[13:05:47] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:472)
[13:05:47] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1579)
[13:05:47] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1238)
[13:05:47] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:324)
[13:05:47] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:1583)
[13:05:47] [Server thread/WARN]: Caused by: java.lang.IllegalArgumentException: missing required data class org.bukkit.Color
[13:05:47] [Server thread/WARN]: 	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:218)
[13:05:47] [Server thread/WARN]: 	at org.bukkit.craftbukkit.CraftParticle.createParticleParam(CraftParticle.java:68)
[13:05:47] [Server thread/WARN]: 	at org.bukkit.craftbukkit.entity.CraftPlayer.spawnParticle(CraftPlayer.java:2981)
[13:05:47] [Server thread/WARN]: 	at org.bukkit.craftbukkit.entity.CraftPlayer.spawnParticle(CraftPlayer.java:2971)
[13:05:47] [Server thread/WARN]: 	at org.bukkit.craftbukkit.entity.CraftPlayer.spawnParticle(CraftPlayer.java:2951)
[13:05:47] [Server thread/WARN]: 	at org.bukkit.craftbukkit.entity.CraftPlayer.spawnParticle(CraftPlayer.java:2941)
[13:05:47] [Server thread/WARN]: 	at ViaRewind-Legacy-Support.jar//com.viaversion.viarewind.legacysupport.feature.AreaEffectCloudEmulator.lambda$new$3(AreaEffectCloudEmulator.java:66)
[13:05:47] [Server thread/WARN]: 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
[13:05:47] [Server thread/WARN]: 	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
[13:05:47] [Server thread/WARN]: 	at java.base/java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1715)
[13:05:47] [Server thread/WARN]: 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
[13:05:47] [Server thread/WARN]: 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
[13:05:47] [Server thread/WARN]: 	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
[13:05:47] [Server thread/WARN]: 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
[13:05:47] [Server thread/WARN]: 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[13:05:47] [Server thread/WARN]: 	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
[13:05:47] [Server thread/WARN]: 	at ViaRewind-Legacy-Support.jar//com.viaversion.viarewind.legacysupport.feature.AreaEffectCloudEmulator.lambda$new$4(AreaEffectCloudEmulator.java:64)
[13:05:47] [Server thread/WARN]: 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
[13:05:47] [Server thread/WARN]: 	at ViaRewind-Legacy-Support.jar//com.viaversion.viarewind.legacysupport.feature.AreaEffectCloudEmulator.lambda$new$5(AreaEffectCloudEmulator.java:45)
[13:05:47] [Server thread/WARN]: 	at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:101)
[13:05:47] [Server thread/WARN]: 	at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:482)
[13:05:47] [Server thread/WARN]: 	... 6 more
```

The issue started occurring after updating from 1.20.4 to 1.20.6

**Comment by Electronik21** [comment]
Also getting this on 1.21

**Comment by FlorianMichael** [comment]
Thank you for reporting the issue, you can download dev builds with the bug fixed on Hangar. https://hangar.papermc.io/ViaVersion/ViaRewindLegacySupport
