### ISSUE TITLE
NoSuchMethodException: net.minecraft.server.v1_16_R3.SoundEffectType.e()

### ISSUE THREAD

**Issue by mibby** [ViaVersion/ViaRewind-Legacy-Support#9]
Paper dev 457 (Spigot 1.16.5)
ViaVersion-DEV dev 414
ViaBackwards-DEV dev 250
ViaReind-DEV dev 187
ViaRewind Legacy Support dev 8

ViaRewind-Legacy-Support spams this error in my logs.

```
brewing-stand-gui-fix: true
enchanting-gui-fix: true
lily-pad-fix: true
ladder-fix: true
sound-fix: true
slime-fix: true
elytra-fix: true
area-effect-cloud-particles: true
```

```
[13:10:59] [Server thread/WARN]: java.lang.NoSuchMethodException: net.minecraft.server.v1_16_R3.SoundEffectType.e()
[13:10:59] [Server thread/WARN]: 	at java.base/java.lang.Class.getMethod(Class.java:2122)
[13:10:59] [Server thread/WARN]: 	at de.gerrygames.viarewind.legacysupport.listener.SoundListener.playBlockPlaceSound(SoundListener.java:120)
[13:10:59] [Server thread/WARN]: 	at de.gerrygames.viarewind.legacysupport.listener.SoundListener.onBlockPlace(SoundListener.java:61)
[13:10:59] [Server thread/WARN]: 	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1285.execute(Unknown Source)
[13:10:59] [Server thread/WARN]: 	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
[13:10:59] [Server thread/WARN]: 	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76)
[13:10:59] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[13:10:59] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:611)
[13:10:59] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callBlockPlaceEvent(CraftEventFactory.java:377)
[13:10:59] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.ItemStack.placeItem(ItemStack.java:280)
[13:10:59] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.PlayerInteractManager.a(PlayerInteractManager.java:566)
[13:10:59] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1635)
[13:10:59] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.PacketPlayInUseItem.a(PacketPlayInUseItem.java:27)
[13:10:59] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.PacketPlayInUseItem.a(PacketPlayInUseItem.java:5)
[13:10:59] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:43)
[13:10:59] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18)
[13:10:59] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
[13:10:59] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
[13:10:59] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
[13:10:59] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1220)
[13:10:59] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1213)
[13:10:59] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119)
[13:10:59] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1189)
[13:10:59] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1029)
[13:10:59] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:176)
[13:10:59] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:832)
```

**Comment by camdenorrb** [comment]
Same issue for us
